name: openidconnect
description: OpenIdConnect library for flutter.
version: 1.0.17-Beta.2
homepage: https://github.com/Concerti-IO/openidconnect_flutter
publish_to: https://pub.dev/openidconnect

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  openidconnect_platform_interface: ^1.0.2
  openidconnect_web: ^1.0.10
  flutter_secure_storage: ^5.0.0-beta.4
  jwt_decoder: ^2.0.1

  cryptography: ^2.0.2

  url_launcher: ^6.0.9
  http: ^0.13.3
  retry: ^3.1.0

  # TODO Remove these once native implementations can be added. Refactor so that the native implementations don't need to do the full cycle through.
  webview_flutter: ^2.0.10

dev_dependencies:
  pedantic: ^1.10.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        default_package: openidconnect_web
